name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build ruby
      env:
        DestinationPath:  /tmp/rubyd
        Major: '2.4'
        Minor: '9'
        InstallationPath: /tmp/ruby
        ToolsDirectory:  /opt/hostedtoolcache/
        Architecture: x64
      run: |
        set -x
        sudo apt-get install -y libreadline-dev libedit-dev wget
        wget https://cache.ruby-lang.org/pub/ruby/${Major}/ruby-${Major}.${Minor}.tar.gz
        tar -xzf ruby-${Major}.${Minor}.tar.gz
        pushd ruby-${Major}.${Minor}
        ./configure --prefix=/tmp/ruby
        make
        make install
        popd
        ls -l /tmp/ruby
        export PATH=/tmp/ruby/bin:$PATH
        which ruby
        ruby -v
        gem environment
        which bundler
        bundler -v
        gem install bundler
        which bundler
        bundler -v
